site_name: qablet_contracts
theme:
  name: material
  icon:
    logo: material/triangle

plugins:
  - search
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          paths: [qablet_contracts]
          options:
            members_order: source
            show_root_toc_entry: false

extra_css:
  - stylesheets/extra.css

nav:
  - 'index.md'
  - 'Specifications':
    - 'specifications/timetable.md'
    - 'specifications/operations.md'
    - 'specifications/units.md'
    - 'specifications/expressions.md'
    - 'specifications/phrase.md'
    - 'specifications/snapper.md'
    - 'specifications/batch.md'
  - 'Examples':
    - Bond:
      - 'examples/bond_zero.md'
      - 'examples/bond_fixed.md'

    - Equity:
      - 'examples/equity_vanilla.md'
      - 'examples/equity_cliquet.md'
      - 'examples/equity_rainbow.md'
    - Rate:
      - 'examples/rate_swaption.md'
