site_name: Qablet Contracts
theme:
  name: material
  palette:
    # Palette toggle for dark mode
    - scheme: slate
      primary: brown

      toggle:
        icon: material/brightness-4
        name: Switch to light mode

    # Palette toggle for light mode
    - scheme: default
      primary: brown

      toggle:
        icon: material/brightness-7 
        name: Switch to dark mode


  logo: assets/logo.png
  features:
    - navigation.tabs

markdown_extensions:
  - admonition
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences

plugins:
  - search
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          paths: [qablet_contracts]
          options:
            members_order: source
            show_root_toc_entry: false

extra_css:
  - stylesheets/extra.css

extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

nav:
  - 'Specifications':
    - 'index.md'
    - 'specifications/timetable.md'
    - 'specifications/operations.md'
    - 'specifications/units.md'
    - 'specifications/tracks.md'
    - 'specifications/expressions.md'
    - 'specifications/phrase.md'
    - 'specifications/snapper.md'
    - 'specifications/batch.md'
  - 'Contracts':
    - Bond:
      - 'examples/bond_zero.md'
      - 'examples/bond_fixed.md'
    - Equity:
      - 'examples/equity_vanilla.md'
      - 'examples/equity_barrier.md'
      - 'examples/equity_fwdoption.md'
      - 'examples/equity_cliquet.md'
      - 'examples/equity_rainbow.md'
      - 'examples/equity_autocall.md'
    - Rate:
      - 'examples/rate_swap.md'
      - 'examples/rate_swaption.md'
